<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_LOGIN_gambar</name>
   <tag></tag>
   <elementGuidId>05f8f334-927d-452c-b0b1-2c823060c389</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.gambar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7fc47456-943d-4700-badc-dc606b252b21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gambar</value>
      <webElementGuid>6e5bc274-7e35-47f9-a031-ba9357297355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/icon/login-18.png</value>
      <webElementGuid>a8bbdfd9-5aa5-4a14-86d3-67bd90eafac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/div[@class=&quot;wrap-gambar&quot;]/img[@class=&quot;gambar&quot;]</value>
      <webElementGuid>4478eada-df4e-4b10-9600-512064d28294</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>9e420aac-16f2-42b8-9016-456ccc9d6978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/icon/login-18.png']</value>
      <webElementGuid>194d4b40-9826-40e2-b396-23bf8aa55d1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
